### ISSUE TITLE
Textureless block and skills

### ISSUE THREAD

**Issue by KamiSami** [Tamaized/AoV#10]
I do not believe this is normal since i saw screenshots of your mod without these texture bugs. Here's screenshots: 

http://pasteboard.co/3obnklYTG.png

http://pasteboard.co/3obQWYiTy.png

**Comment by Tamaized** [comment]
I'm going to assume 1.10.2?

**Comment by KamiSami** [comment]
Yep.

**Comment by Tamaized** [comment]
I hate 1.10 >.> It'll be fixed along with the other crash

**Comment by KamiSami** [comment]
Alright, thanks for looking into these.
