### ISSUE TITLE
Crash upon entering world

### ISSUE THREAD

**Issue by desmfn** [Tamaized/AoV#107]
On latest 1.12.2 version with several other mods
No problem while loading the game, but freeze when trying to entering a world and generates crash reports
[crash-2019-02-11_20.59.14-client.txt](https://github.com/Tamaized/AoV/files/2854172/crash-2019-02-11_20.59.14-client.txt)
[crash-2019-02-11_20.59.07-server.txt](https://github.com/Tamaized/AoV/files/2854173/crash-2019-02-11_20.59.07-server.txt)

**Comment by Tamaized** [comment]
This is an issue with DummyCoreUnofficial

**Comment by Tamaized** [comment]
Actually that was the client report.

The Server report means you need to update Forge. See #102
