### ISSUE TITLE
Creative mode only?

### ISSUE THREAD

**Issue by Tokenyet** [Tamaized/AoV#117]
I installed this mod, found a lot of strange things, I have never used this mod before, so It could be some misunderstanding.

Here is what I tried, but seems to be unexpected:

1. Sleep to Recharge the ability not working. I saw the comments from curseforge that someone told me could recharge It on sleeping, but I cannot recover It, It still be unused(red) state.

2.  Creative mode working, but nothing work with other gamemode, I first test the mode with Creative mode, The SkillList was on the top, but when I switched to other mode, the UI disappearing, but still could change and use the ability by pressing ALT and number changing.

3. The last thing, what is handwraps going to do? It didn't do anything when I hold It, and even nothing showing, just like holding empty.

Scenario:
Forge Version: 1.13.2 - 25.0.99

**Comment by Tamaized** [comment]
First two are bugs, third thing is normal. Handwraps are a weapon used by druid and monk (when I get around to adding that)

**Comment by Tamaized** [comment]
I've fixed the first issue but can't seem to reproduce the second issue. Seems to be working fine for me which is odd.

**Comment by GrifVindh** [comment]
I just wanted to add that I'm also having this issue. Originally I thought it wasn't working at all (I could build the statue but right-clicking on it did nothing) but when I switched over to creative mode it worked as expected. I could then switch back into survival and cast spells, but I have to switch back into creative any time I want to interact with the statue.

I don't think it's a mod conflict. I tried unloading every mod I use except for Angel, and I still experience it.

I'm running OpenJDK 8 on Linux. I haven't tried testing it on windows yet, but I think I will just to see if it's any different.

**Comment by GrifVindh** [comment]
OK, I just tested it in Windows 10 -- it's the same issue. I have to be in creative mode to trigger the statue UI, although after selecting a class I can switch back to survival and cast spells.

**Comment by Tamaized** [comment]
You're using the wrong statue, unless you mean it's all of them that have the issue.

**Comment by GrifVindh** [comment]
Ah! Well that may be, but if so then your "Getting Started" information on Curse appears to be a little out of date. I created the statute shown there, with the understanding (based on what was posted) that I needed to right click on that in order to choose a class.

**Comment by Tamaized** [comment]
Yeah I'm aware that's outdated (even says so near the top) I'm getting around to updating it when I have time.

**Comment by GrifVindh** [comment]
So what kind of statue do I need to build to start it off? I guess my issue has nothing to do with the original post at all, I'm just suffering from basic ignorance. :-/

**Comment by Tamaized** [comment]
Each class has their own statue now. Can use JEI to get the recipes. I'd screenshot em but I'm not off work till 4pm EST :p

**Comment by Tamaized** [comment]
Can also look here https://github.com/Tamaized/AoV/tree/1.13/src/main/resources/data/aov/recipes

**Comment by GrifVindh** [comment]
OK, based on that information I can now confirm that I am not experiencing the original issue -- I was, in fact, simply building the wrong statute. Apologies for derailing the bug report.

**Comment by Tokenyet** [comment]
Thanks for the updated! I've updated the mod in this week, all the issue seem to be sloved.  👍
