### ISSUE TITLE
Multiplayer Weirdness

### ISSUE THREAD

**Issue by GrifVindh** [Tamaized/AoV#119]
I've noticed some weird performance issues when more than one person with this mod tries to play on the same server. I don't know if it's that the mod simply wasn't designed for use in multiplayer, or if I've configured something incorrectly, but essentially it's as if each person with the mod is competing over the same toolbar.

Example: two people log into a server with the mod and try to access the spell bar at the same. Both people report that the spell bar shows up for an instance, and then it reverts back to the normal inventory bar. Also, if two people try to click on the same statue at the same time, they wind up spending each other's spell points.

Everything works exactly the way you expect it to when there is only person playing in a world.

**Comment by Tamaized** [comment]
Just to make sure, LAN or Dedicated Server?

**Comment by GrifVindh** [comment]
LAN, not dedicated server. Just on my home network.

**Comment by Tamaized** [comment]
Also want to ask, was this just in 1.13.2 or 1.12.2 or every version?

**Comment by GrifVindh** [comment]
1.13.2 - haven't been playing earlier versions, so I don't know if it affects them.
