### ISSUE TITLE
Are you supposed to lose your magic levels when you die?

### ISSUE THREAD

**Issue by GrifVindh** [Tamaized/AoV#120]
I've noticed that in game a character who does loses all their accumulated magic levels. Is this an intended game mechanic?

**Comment by Tamaized** [comment]
It's not intended, if this is 1.13.2, forge 1.13 is still in beta and I'm still trying to figure out what's not quite working and what is in forge. Seems the clone event is busted.

**Comment by GrifVindh** [comment]
It is 1.13.2 forge. I'll adjust accordingly. :-)

**Comment by Tamaized** [comment]
Mkay
(this is the whole reason I uploaded alpha builds, to find bugs cuz I wouldn't have found this one any time soon)

Anywho, I've actually got time today so I'll get around to squashing bugs when I get home.

**Comment by GrifVindh** [comment]
Well for an alpha build it actually works extremely well.
