### ISSUE TITLE
[1.13.2] /aov command fails when providing a player

### ISSUE THREAD

**Issue by Tokenyet** [Tamaized/AoV#123]
I found out a command feature in your history commit, but It is not able to use like `/aov` prefix in the game. I'm wondering If this is implemented in 1.13.2?

The commit you implemented, but I cannot use any of command in the latest 1.13.2 aov 😢 
https://github.com/Tamaized/AoV/commit/7ba4674d05773ec590d0391a4676cdb5547a5c0e

By the way, What is debugger item used for? I have no idea how to use It 😕

**Comment by Tamaized** [comment]
The aov command should be working fine, I've been using it myself in 1.13.2. I haven't tested it on servers however, is this on a server?

The debugger is for my own use.

**Comment by GrifVindh** [comment]
I have successfully used /aov but I have noticed that when I try to use a player name it fails. If I use it without a player name (i.e. on myself) it works fine.
