### ISSUE TITLE
AoV requires forge version in use

### ISSUE THREAD

**Issue by Martmists-GH** [Tamaized/AoV#128]
My client fails to launch with the following message:

```
net.minecraftforge.fml.common.MissingModsException: Mod aov (Angel of Vengeance) requires [forge[14.23.5.2808,)]
```

However, forge 14.23.5.2808 is the version in use.
14.23.5.2825 fails with the same error

**Comment by Tamaized** [comment]
Post the log

**Comment by Martmists-GH** [comment]
Would the problem be that it required `forge@` instead of `forge` in mcmod.info?

**Comment by Martmists-GH** [comment]
Here's the log of our server https://pastebin.com/wmRPd77b

**Comment by Tamaized** [comment]
Yup forgot the @, that's what I get for rushing at 5am right before work. You can downgrade a single aov version, the entire point if the latest was to force users on to a specific forge version to avoid a crash with earlier builds. There was no content added in this build.

I'll take down the current latest and fix it when I'm home from work.

**Comment by Martmists-GH** [comment]
Will this be pushed to CF soon?

**Comment by Tamaized** [comment]
Already is, I reused the same version number

**Comment by Martmists-GH** [comment]
The current 0.11.5 still is broken though, reporting the same issue on our server.

**Comment by Tamaized** [comment]
Odd, I even recall testing it fully before upload. You're 100% sure this is the new build?

**Comment by Martmists-GH** [comment]
yup, it's the one pinned on the right hand side on curseforge

**Comment by Tamaized** [comment]
I'll recheck everything when I get home in a few hours

**Comment by Tamaized** [comment]
Seems to be working fine:
![image](https://user-images.githubusercontent.com/9671313/56394221-9cb4da00-6204-11e9-8337-adba3ce30dff.png)


And loads with a proper forge version:
![image](https://user-images.githubusercontent.com/9671313/56394263-bfdf8980-6204-11e9-95be-72c46a5a0d9a.png)
