### ISSUE TITLE
How to give hability points ?

### ISSUE THREAD

**Issue by Finelarme9** [Tamaized/AoV#130]
Hello
How can I make my hability tests/give me some hability points to use please ?
Thank you for your stuffs.
Ben

**Comment by Tamaized** [comment]
I don't understand.

**Comment by Finelarme9** [comment]
Sorry. I mean : If I must get experience manually I will need a ton of hours to test all the spells. Or there is another way ?

**Comment by Tamaized** [comment]
The Debugger/Debug Tool (idk what i named it) from the mod gives a level upon right click.

You may also use `/aov setlevel 15` or whatever level you want as the number

**Comment by Finelarme9** [comment]
It is perfect. Thank you for your answer !
