### ISSUE TITLE
Clarify Recharge Rate config option

### ISSUE THREAD

**Issue by Teibidh** [Tamaized/AoV#134]
My private pack's play group almost never sleeps which makes recharging AoV spells very impractical. With the current Integer only options recharge happens very quickly making spell use virtually unlimited. Making this a Float would allow server operators to scale recharge to their desired power scale while preserving the "limited resource" intent of the mod.

**Comment by Tamaized** [comment]
>very quickly

The config option is in ticks. Making that a float doesn't make any sense.

**Comment by Teibidh** [comment]
How about we reword the description in the config, then? Currently it reads:
"Sets the recharge rate per tick, -1 disables this" This led me to believe that this was how many charges I was regenerating per tick, not the other way around.

Fantastic mod, my players all love it... just looking for some QoL love is all.
