### ISSUE TITLE
Controls menu crashes game

### ISSUE THREAD

**Issue by Jack-Chronicle** [Tamaized/AoV#14]
Whenever I try to open the controls menu with the mod installed, minecraft crashes

**Comment by Tamaized** [comment]
Version and CrashLog ?

**Comment by Jack-Chronicle** [comment]
Minecraft  1.12
Forge 14.21.0.2322
AoV-1.12-0.3.2
TamModized-1.12-0.10.1
Crash Report:

[crash-2017-06-12_20.05.03-client.txt](https://github.com/Tamaized/AoV/files/1070097/crash-2017-06-12_20.05.03-client.txt)

**Comment by Tamaized** [comment]
Had to dig into the vanilla code to figure this out, turns out it's a vanilla/forge bug from the 1.12 update but I can work around it. Will get a new build out for it soon.

**Comment by Jack-Chronicle** [comment]
That would be awesome. And thanks for the quick response/work
