### ISSUE TITLE
[1.12.2] The altar doesn't render properly.

### ISSUE THREAD

**Issue by ProsperCraft** [Tamaized/AoV#147]
Settings-
![2020-02-26_13 58 34](https://user-images.githubusercontent.com/4427684/75387212-34ad3680-58a0-11ea-8031-da1c69b91c07.png)

Visuals-
![2020-02-26_13 56 10](https://user-images.githubusercontent.com/4427684/75387280-54445f00-58a0-11ea-9686-6c39c2abbde8.png)
![2020-02-26_13 56 13](https://user-images.githubusercontent.com/4427684/75387286-58707c80-58a0-11ea-8b7f-9b92f68d564b.png)
![2020-02-26_13 56 19](https://user-images.githubusercontent.com/4427684/75387296-5b6b6d00-58a0-11ea-9a7a-9375e240d46c.png)

Modpack- Ancient TownCraft 0.95

AoV-1.12-0.11.5

**Comment by Tamaized** [comment]
Some other mod most likely has a bad gl state leak. My blocks are nothing more than generic baked models. Unless you can somehow reproduce this with AoV alone... which means the leak would be on my end but till then i'm closing this.
