### ISSUE TITLE
Server crash, log included

### ISSUE THREAD

**Issue by mandychuu** [Tamaized/AoV#149]
I'm using Apex Hosting to host my server -- pretty new to it, though I can somewhat read crash logs and find the root cause of an issue.

So far, the server has crashed twice on me today. Both seems to have happened sometime after I disconnect without another player on the server and after the server auto-saves.
[crash-2020-03-25_13.24.09-server.txt](https://github.com/Tamaized/AoV/files/4383385/crash-2020-03-25_13.24.09-server.txt)

**Comment by Tamaized** [comment]
Duplicate #148
