### ISSUE TITLE
Angelic Block has poor creation checks

### ISSUE THREAD

**Issue by NielsPilgaard** [Tamaized/AoV#19]
Minecraft 1.12
Forge 14.21.1.2406
AoV 1.12-0.4.1

Heya. I attempted to make the structure to begin the mod on my server - It seemed to work well at first, as the altar appeared, but it vanished shortly after, along with the diorite. The andesite didn't disappear, and most of the granite was replaced with netherrack.

I'm pretty sure I made the structure correctly, as I've made it several times in single player.

**Comment by Tamaized** [comment]
Can't seem to reproduce.

**Comment by NielsPilgaard** [comment]
Fair enough, I'll try to find the cause :)

**Comment by NielsPilgaard** [comment]
I finally found it! Somehow, your mod is conflicting with Psi, and vice-versa.
Would you like a forced crashlog or something?

**Comment by Tamaized** [comment]
Huh, that's weird. I'm currently using psi and my own mod here in a private pack (and server) and still haven't ran into this issue. The structure does however require that there aren't any blocks around anywhere in the `box` I guess you can call it. My checks aren't that great and needs to be rewritten so it's possible a block is in the way somewhere. Think of it like Botania's gaia guardian setup and how it requires an open area for now.

**Comment by NielsPilgaard** [comment]
Is the structure still valid if blocks touch the bottom Andesite/Granite, on the bottom or sides?
That's really weird, I suppose there's another mod conflicting aswell.

**Comment by Tamaized** [comment]
Bottom is fine but sides are not. That's my shit code in play right there. Once I have time I'll go in and overhaul the checks.

**Comment by NielsPilgaard** [comment]
Damnit, I was really hoping I was just making the structure poorly, that would've been so much easier :p

**Comment by Tamaized** [comment]
Heh, i'll leave this open as a reminder for me to fix this though.

**Comment by Tamaized** [comment]
My mistake, it doesn't check for air blocks besides right where my crosshair is pointing. The checks are still pretty bad though and need to be cleaned up. Hmm, something really odd is going on then for these issues to occur as I myself have ran into em.
![2017-08-17_20 33 27](https://user-images.githubusercontent.com/9671313/29443237-899b9836-838b-11e7-97cf-05f3638d0d5f.png)

**Comment by NielsPilgaard** [comment]
Have you made any progress on this? :)

**Comment by NielsPilgaard** [comment]
Thank you!
