### ISSUE TITLE
Spell targetting height

### ISSUE THREAD

**Issue by Zygus42** [Tamaized/AoV#20]
AoV-1.12-0.4.1
Tested this mod by shooting spells at Zombies.  If the Zombie's feet are covered by anything, such as grass or by being in a 1 deep hole, the spell does not hit.  If the Zombie is standing in a 1 deep hole, it is impossible to hit them, unless you're standing immediately next to them pointing downwards, or you're flying almost directly above them.  Really the spells ought to be going from Steve's head height to Zombie's head height, not feet height.

**Comment by Tamaized** [comment]
Was this on a sponge server because that is not how raytracing hitboxes work nor have I seen this issue in testing or playing normally.

**Comment by Zygus42** [comment]
Standard forged minecraft.

AoV-1.12-0.4.1
forge-1.12-14.21.1.2428-installer-win

No other mods at all as I'm testing each mod individually before putting into new modpack.

**Comment by Tamaized** [comment]
Unable to reproduce
