### ISSUE TITLE
0.5.1 Infinite Gl Error loop in log

### ISSUE THREAD

**Issue by mcfilmmakers** [Tamaized/AoV#24]
I have version 0.5.1 running and regardless of forge version, I get an infinite GL Error report in my log.

Normally I would ignore it but it makes my log file way too big in file size to be acceptable:

[18:58:45] [main/ERROR]: ########## GL ERROR ##########
[18:58:45] [main/ERROR]: @ Post render
[18:58:45] [main/ERROR]: 1281: Invalid value
[18:58:45] [main/ERROR]: ########## GL ERROR ##########
[18:58:45] [main/ERROR]: @ Post render
[18:58:45] [main/ERROR]: 1281: Invalid value
[18:58:45] [main/ERROR]: ########## GL ERROR ##########
[18:58:45] [main/ERROR]: @ Post render
[18:58:45] [main/ERROR]: 1281: Invalid value
[18:58:45] [main/ERROR]: 1281: Invalid value
.... repeat ad infinitum ....

Removing Angel of vengeance stops the error from happening. This is true whether I have 100+ mods running or Angel of Vengeance running alone.

**Comment by Tamaized** [comment]
When does this happen exactly? On startup or was there some trigger?

**Comment by mcfilmmakers** [comment]
It happens when I get into the main menu of the game. No world created yet, fresh install.

**Comment by mcfilmmakers** [comment]
I don't have to do anything. I don't even move the mouse or click any buttons.

**Comment by mcfilmmakers** [comment]
It doesn't happen with any other mod. (Sorry about the many replies)

**Comment by antoinegag** [comment]
Does it happen without the mod?
I've seen that happen in Vanilla.

**Comment by Tamaized** [comment]
^ yes it's been said it doesn't happen without the mod, I'll be looking into this later when I can ~

**Comment by Tamaized** [comment]
I actually can't seem to reproduce this. I expected there to be some GL leak I missed from my last bug fix commit but that doesn't seem to be the case. I even traced through the code to ensure there wasn't a state leak.

**Comment by mcfilmmakers** [comment]
Turns out the error is cause by Albedo when it is paired with other mods and forge has a problem loading something... easily reproduced when it is paired with a mod that has a dependency (Such as Angels of vengeance) but the dependency is not present.
