### ISSUE TITLE
Move everything over to a lang file

### ISSUE THREAD

**Issue by kizza5161** [Tamaized/AoV#25]
![image](https://user-images.githubusercontent.com/31421918/30406576-de416784-991c-11e7-98fc-b7b3a2bb7134.png)

Hi, I am using a dedicated server for my friend group Sponge fake version running 1.10.2 I want to add your mod to enrich in the game. But the mod is limited to certain versions. :)
- Can you upgrade it to use for the latest forge version?

We are not good at English, the usual mods have lang files and I translate them into my national language so my friends will not have difficulty playing. :)
- Can you update the full contents of mod in en_US.lang?

Thank you

**Comment by kizza5161** [comment]
.

**Comment by Tamaized** [comment]
1.10.2 isn't supported.

However, the lang file is still on my todo list.

**Comment by kizza5161** [comment]
1.10.2 không được hỗ trợ. Điều đó có nghĩa là nó sẽ không bao giờ được hỗ trợ hoặc vẫn còn trong dự án?

**Comment by kizza5161** [comment]
1.10.2 is not supported. Does that mean it will never be supported or still in the project?

**Comment by Tamaized** [comment]
1.10.2 is no longer going to be updated.

Anyway, renaming this to be for a lang file and i'll get that done asap~
