### ISSUE TITLE
Crashes when I use any ability

### ISSUE THREAD

**Issue by Zenikackerman** [Tamaized/AoV#27]
Sorry, I have never sent a crash report and I suppose this is what I have to send...

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  BCModPlugin (backpacks 1.12.2 - 3.3.2.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 10/24/17 5:10 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: tamaized/tammodized/common/helper/PacketHelper
	at tamaized.aov.common.capabilities.aov.AoVCapabilityHandler.cast(AoVCapabilityHandler.java:456)
	at tamaized.aov.client.events.KeyHandler.handleMouse(KeyHandler.java:63)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_229_KeyHandler_handleMouse_MouseEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.postMouseEvent(ForgeHooksClient.java:226)
	at net.minecraft.client.Minecraft.func_184124_aB(Minecraft.java:2273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1798)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: tamaized.tammodized.common.helper.PacketHelper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at tamaized.aov.common.capabilities.aov.AoVCapabilityHandler.cast(AoVCapabilityHandler.java:456)
	at tamaized.aov.client.events.KeyHandler.handleMouse(KeyHandler.java:63)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_229_KeyHandler_handleMouse_MouseEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.postMouseEvent(ForgeHooksClient.java:226)
	at net.minecraft.client.Minecraft.func_184124_aB(Minecraft.java:2273)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['JoakGrang'/78, l='MpServer', x=-518.42, y=4.00, z=-276.68]]
	Chunk stats: MultiplayerChunkCache: 1056, 1056
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-379,4,-800), Chunk: (at 5,0,0 in -24,-50; contains blocks -384,0,-800 to -369,255,-785), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 24697 game time, 36666 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 45 total; [EntitySlime['Slime'/260611, l='MpServer', x=-477.42, y=5.18, z=-313.42], EntityLatchedRenderer['unknown'/17796, l='MpServer', x=-518.42, y=4.00, z=-276.68], EntitySlime['Slime'/425601, l='MpServer', x=-524.84, y=4.72, z=-207.53], EntitySlime['Slime'/440590, l='MpServer', x=-463.30, y=4.12, z=-339.99], EntitySlime['Slime'/374153, l='MpServer', x=-458.27, y=4.00, z=-315.89], EntityLatchedRenderer['unknown'/141, l='MpServer', x=-514.17, y=5.00, z=-259.12], EntitySlime['Slime'/139148, l='MpServer', x=-516.65, y=4.00, z=-291.51], EntitySlime['Slime'/415126, l='MpServer', x=-485.35, y=4.00, z=-317.59], EntitySlime['Slime'/421269, l='MpServer', x=-468.96, y=4.00, z=-319.79], EntitySlime['Slime'/209941, l='MpServer', x=-598.19, y=4.83, z=-308.70], EntitySlime['Slime'/349854, l='MpServer', x=-577.60, y=4.00, z=-313.95], EntityItem['item.item.inventorypets_blue_screen_of_death'/32545, l='MpServer', x=-514.11, y=4.00, z=-260.82], EntitySlime['Slime'/323104, l='MpServer', x=-509.22, y=4.83, z=-282.59], EntitySlime['Slime'/452003, l='MpServer', x=-575.44, y=5.17, z=-309.28], EntitySlime['Slime'/132263, l='MpServer', x=-556.29, y=4.00, z=-198.77], EntitySlime['Slime'/200126, l='MpServer', x=-485.25, y=5.08, z=-322.39], EntitySlime['Slime'/409927, l='MpServer', x=-463.01, y=4.72, z=-289.60], EntitySlime['Slime'/329665, l='MpServer', x=-537.91, y=4.00, z=-233.94], EntitySlime['Slime'/57669, l='MpServer', x=-486.92, y=4.00, z=-290.68], EntitySlime['Slime'/265666, l='MpServer', x=-450.53, y=4.27, z=-340.37], EntityPlayerSP['JoakGrang'/78, l='MpServer', x=-518.42, y=4.00, z=-276.68], EntityLatchedRenderer['unknown'/81, l='MpServer', x=8.50, y=65.00, z=8.50], EntitySlime['Slime'/71763, l='MpServer', x=-524.39, y=4.53, z=-259.14], EntitySlime['Slime'/311389, l='MpServer', x=-587.64, y=4.00, z=-211.77], EntitySlime['Slime'/346585, l='MpServer', x=-516.93, y=4.42, z=-329.76], EntitySlime['Slime'/434137, l='MpServer', x=-592.83, y=4.67, z=-214.59], EntityWolf['Barkley'/96, l='MpServer', x=-507.83, y=4.00, z=-281.48], EntityCreeper['Creeper'/97, l='MpServer', x=-524.33, y=4.00, z=-275.93], EntitySlime['Slime'/98, l='MpServer', x=-549.87, y=4.55, z=-285.87], EntitySlime['Slime'/446564, l='MpServer', x=-587.57, y=4.95, z=-224.45], EntitySlime['Slime'/102, l='MpServer', x=-514.85, y=4.00, z=-217.97], EntitySlime['Slime'/264172, l='MpServer', x=-547.95, y=4.14, z=-201.27], EntitySlime['Slime'/370543, l='MpServer', x=-586.10, y=4.00, z=-213.61], EntitySlime['Slime'/108, l='MpServer', x=-494.36, y=4.00, z=-336.60], EntitySlime['Slime'/428395, l='MpServer', x=-522.12, y=4.42, z=-218.76], EntitySlime['Slime'/175986, l='MpServer', x=-540.56, y=4.00, z=-236.31], EntitySlime['Slime'/485878, l='MpServer', x=-448.50, y=4.00, z=-350.50], EntityItem['item.item.inventorypets_moon_pet'/114, l='MpServer', x=-519.85, y=4.00, z=-285.46], EntityItem['item.item.inventorypets_enderman_pet'/115, l='MpServer', x=-519.15, y=4.00, z=-282.87], EntityItem['item.item.monsterPlacer'/22515, l='MpServer', x=-515.92, y=4.00, z=-262.01], EntityItem['item.item.inventorypets_feed_bag'/116, l='MpServer', x=-519.43, y=4.00, z=-283.75], EntityItem['item.item.inventorypets_double_chest_pet'/117, l='MpServer', x=-519.00, y=4.00, z=-285.17], EntitySlime['Slime'/468347, l='MpServer', x=-552.78, y=4.00, z=-217.76], EntitySlime['Slime'/452091, l='MpServer', x=-488.68, y=4.67, z=-328.00], EntitySlime['Slime'/125, l='MpServer', x=-563.52, y=4.72, z=-342.07]]
	Retry entities: 2 total; [EntityLatchedRenderer['unknown'/81, l='MpServer', x=8.50, y=65.00, z=8.50], EntityLatchedRenderer['unknown'/141, l='MpServer', x=-514.17, y=5.00, z=-259.12]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 466631432 bytes (445 MB) / 1055772672 bytes (1006 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2509 Optifine OptiFine_1.12.2_HD_U_C6 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                | Version                  | Source                                    | Signature                                |
	|:--------- |:----------------- |:------------------------ |:----------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft         | 1.12.2                   | minecraft.jar                             | None                                     |
	| UCHIJAAAA | mcp               | 9.42                     | minecraft.jar                             | None                                     |
	| UCHIJAAAA | FML               | 8.0.99.99                | forge-1.12.2-14.23.0.2509.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge             | 14.23.0.2509             | forge-1.12.2-14.23.0.2509.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | ivtoolkit         | 1.3.3-1.12               | minecraft.jar                             | None                                     |
	| UCHIJAAAA | backpacks16840    | 3.3.2                    | backpacks 1.12.2 - 3.3.2.jar              | None                                     |
	| UCHIJAAAA | mercurius_updater | 1.0                      | MercuriusUpdater-1.12.2.jar               | None                                     |
	| UCHIJAAAA | rpghud            | 3.6.6.2                  | [1.12] RPG-HUD-3.6.6.2.jar                | None                                     |
	| UCHIJAAAA | tammodized        | 0.15.3                   | TamModized-1.12.1-0.15.3.jar              | None                                     |
	| UCHIJAAAA | aov               | 0.4.1                    | AoV-1.12-0.4.1.jar                        | None                                     |
	| UCHIJAAAA | bibliocraft       | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar         | None                                     |
	| UCHIJAAAA | cucumber          | 1.0.2                    | cucumber[1.12]-1.0.2.jar                  | None                                     |
	| UCHIJAAAA | ichunutil         | 7.0.2                    | iChun-Util-Mod-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | ic2               | 2.8.16-ex112             | industrialcraft-2-2.8.16-ex112.jar        | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | inventorypets     | 1.4.9.9                  | inventorypets-1.12-1.4.9.9.jar            | None                                     |
	| UCHIJAAAA | inventorytweaks   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | jei               | 4.7.8.95                 | jei_1.12.1-4.7.8.95.jar                   | None                                     |
	| UCHIJAAAA | journeymap        | 1.12.2-5.5.0rc1          | journeymap-1.12.2-5.5.0rc1.jar            | None                                     |
	| UCHIJAAAA | silentlib         | 2.2.9                    | SilentLib-1.12-2.2.9-89.jar               | None                                     |
	| UCHIJAAAA | sync              | 7.0.0                    | Sync-Mod-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | treechopper       | 1.2.3                    | TreeChopper-1.12.1-1.2.3.jar              | None                                     |
	| UCHIJAAAA | twilightforest    | 3.0.0                    | twilightforest-1.12.2-3.0.0-universal.jar | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
BCModPlugin (backpacks 1.12.2 - 3.3.2.jar)
  brad16840.common.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13476 Compatibility Profile Context 22.19.171.257' Renderer: 'AMD Radeon R7 200 Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.0.2509
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R7 200 Series GL version 4.5.13476 Compatibility Profile Context 22.19.171.257, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_C6
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13476 Compatibility Profile Context 22.19.171.257
	OpenGlRenderer: AMD Radeon R7 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6

**Comment by Tamaized** [comment]
whoops, i broke AoV when I updated TamModized, i'll get a fix out soon

**Comment by Tamaized** [comment]
Actually.. it's already been fixed. Update your AoV.

You're on ver 0.4.1 but the latest is 0.6.2

**Comment by Zenikackerman** [comment]
omg sorry haha thanks for answering
