### ISSUE TITLE
Rebalance everything

### ISSUE THREAD

**Issue by Tamaized** [Tamaized/AoV#30]
Initially all values we're mostly just placeholder until the mod was finished then I was going to go in and fix it all up.

Right now things are insanely overpowered/underpowered and needs to be toned down/up.

 - Exp is all 20 base, add some variety
 - Damage Values are a bit nuts
 - Flesh out bonus values (spellpower, charges, dodge, doublestrike)
 - Defender Vigor really shouldn't be 5 hearts for free, you're crazy to not go for this, make it require a shield in hand PLEASE.

**Comment by EPIICTHUNDERCAT** [comment]
I agree with damage values haha! CRAZY OP.

**Comment by cjm721** [comment]
The fact that there is an ability (Slay living) that will kill anything that is living and not a boss is a bit breaking. Also that if you really want to kill something set its HP to zero rather then doing this, and before just check if they are invulnerable.

https://github.com/Tamaized/AoV/blob/75f2ec01dd6ac4d1af23068b28c39bd7273e0b42/src/main/java/tamaized/aov/common/core/abilities/caster/SlayLiving.java#L86
