### ISSUE TITLE
[1.12.2 - 0.6.2] Right Click Key isn't corresponding to KeyBind!

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [Tamaized/AoV#33]
Heya Tam! Great damn mod!! So far im loving this mod, OP but great. I just had one small issue. due to the way I play I dont use the right click on a mouse, I change it to something else, when I do this, the mod doesnt listen to the keybind change. dont know if it is hardcoded to be the right click key only but It makes it difficult to actually use the mod the way I play :P nothing major just something nice to be able to switch <3

Horizons 3 Pack
Forge: 2515

**Comment by cjm721** [comment]
More then just him, common a lot of Mac users.

Also prevents interacting with anything when you have abilities selected for normal right click users.
