### ISSUE TITLE
Bug: Losing Spells and XP on Death Until Relog/Restart

### ISSUE THREAD

**Issue by DinixM** [Tamaized/AoV#36]
As the the title says, I've been losing access to my spells upon death, like I dropped them as items. I don't get them back upon reclaiming my Gravestone. Checking the Angel Statue shows that I'm at level 1, even though I was at 3 and above upon my demise. I cannot access my spells at all until exiting and reloading the world, and spending points in this bugged state wastes them after reloading. Using the mod in DW20 pack, added manually, 1.12.2, Minecraft Forge 14.23.0.2551.  Mod was added into a preexisting world.

**Comment by Tamaized** [comment]
Hrm, seems my capability broke. oops. Will fix it when I have time.

**Comment by DinixM** [comment]
Thank you so much. Have a wonderful day.

**Comment by Tamaized** [comment]
1 line code bug fixes are the best
