### ISSUE TITLE
[1.12.2 v0.7.5] Can't pick a class

### ISSUE THREAD

**Issue by VallenFrostweaver** [Tamaized/AoV#37]
When you start out on v0.7.5 you can't pick a class to start. 0.7.4 seems to work fine.

**Comment by Tamaized** [comment]
Whoops, will be fixed asap

**Comment by Dourmouki** [comment]
i came here to report this but thankfully its gonna be fixed

**Comment by Tamaized** [comment]
easiest fix in my life
