### ISSUE TITLE
Duplicate spells in spell book

### ISSUE THREAD

**Issue by Shahelion** [Tamaized/AoV#39]
Can't actually equip both of the same spell, but I feel like they aren't supposed to be there. At level 5 I had two Aid but only 1 Shield of Faith.

Also, considering how each class really doesn't get that many spells, have you considered making them larger and/or flashier looking? Like big proper spell cards or something? 

![2017-12-03_00 06 19](https://user-images.githubusercontent.com/6917535/33523497-e796a04e-d7bd-11e7-9721-17961b4c7258.png)

**Comment by Tamaized** [comment]
I can't seem to reproduce this one. Did it occur directly after updating the mod?

**Comment by Dhs92** [comment]
Nimbus has been duplicated for me as well, this is after updating.

**Comment by Tamaized** [comment]
Does this occur still after you do a minor reset

**Comment by Dhs92** [comment]
It  does indeed

**Comment by Shahelion** [comment]
Looks like any spells I already knew are copied when starting up the game, but spells learned that session are not copied until fully restarting Minecraft. Never copies spells already copied.

I had the first three spells here already, and just learned Stalwart Pact this session:

![2017-12-09_16 55 20](https://user-images.githubusercontent.com/6917535/33800983-c50bb20a-dd01-11e7-8eee-13e36c44195c.png)

**Comment by Tamaized** [comment]
Does this issue still exist in the latest build?

**Comment by Shahelion** [comment]
It appears to be fixed.
