### ISSUE TITLE
Abilities don't recharge when visiting the statue.

### ISSUE THREAD

**Issue by Dhs92** [Tamaized/AoV#40]
What I said in the title. Sadly, no error messages in the console. It seems to happen with any class, and it affects all users. Mod version 0.8.1 in Horizons III, forge version 14.23.1.2556, and running this on a server.

**Comment by Tamaized** [comment]
Intended, a mechanic was changed recently. You now have to sleep in a bed to regain charges. This was changed due to you being able to craft, break and pickup, the angelic statue. Meaning you would have been able to just keep one on you at all times to regain charges.
