### ISSUE TITLE
Unable to complete Defender skill tree. 

### ISSUE THREAD

**Issue by RubikMonat** [Tamaized/AoV#41]
Issue type:
🐛 Bug
Short description:
Playing the Defender branch in Grimco R&D modpack.
I can't unlock the last few items for defender class even at max experience. 

Expected behaviour:
Should be able to select everything when at XP Cap.

Actual behaviour:
The three items "Stalwart Pact" "Invoke Mass" and "Capstone Defender" remain red. Skill Points 0, spent 15 of 15, Level 15. Max Experience Achieved2

Steps to reproduce the problem:
1: Level up to 14 and select all of the options except listed above.
2: Reach level 15, try to select the remaining items.

Versions:
This mod: 0.8.1
Minecraft: 1.12.2
Forge: 8.0.99.99
Mopdpack: Grimco R&D 1.0.3

**Comment by Tamaized** [comment]
Not a bug, you're capped at 15 skill points to spend at maximum. Defender has 18 skills meaning you have to leave 3 out, you can't just select everything. If you wish to respec then use the Minor Reset function.

**Comment by RubikMonat** [comment]
Ok thanks... will do so. Thanks for the rapid response.
