### ISSUE TITLE
[Request] Stealth Class

### ISSUE THREAD

**Issue by bin4rym4ge** [Tamaized/AoV#42]
- Sneaking

- temporary invisibility

- backstab/stealth multiplier

- stealth armor/stealth set bonus #29 

- fast swinging daggers

- higher stealth multipliers for dagger damage

is a stealth class possible?

**Comment by Shahelion** [comment]
Is this intended to be a PvP class, or is it possible to implement an invisibility that would also hide the player from mobs?

**Comment by Tamaized** [comment]
Actually decided to not go with this, the aim of the mod is more holy based or healer based classes.
