### ISSUE TITLE
[Suggestion] Replace checks instanceof ItemShield with isShield checks

### ISSUE THREAD

**Issue by mallrat208** [Tamaized/AoV#43]
This mostly for cross mod compatibility and is not strictly needed but would be very nice to have.

AoV currently is coded to check for Shields either are or extend vanilla's ItemShield. The problem with this is that a good number of mods don't actually do that. They just make their own item using their existing base item or the like. The end result is that you cannot use their shields with AoV. Item has a method, isShield that should probably be used instead to check if a given item actually is a shield or not.

I went ahead and tried this out locally already, replacing the four instances of instanceof checks and everything's worked as expected

**Comment by Tamaized** [comment]
Oh nice, I wasn't even aware of that method.

**Comment by mallrat208** [comment]
From my understanding it was implemented by Forge in 1.12 or close to it, it didn't originally exist when shields became a thing for modded minecraft.
