### ISSUE TITLE
Translation of zh_tw

### ISSUE THREAD

**Issue by sfs131010** [Tamaized/AoV#45]
Hi Tamaized,
For Chinese players can play this mod easier, I translated your mod to Chinese, the version is 1.12.2 and hope you can update with my translation, thank you.
[zh_tw.zip](https://github.com/Tamaized/AoV/files/1584112/zh_tw.zip)
Github does not support .lang file type and it is my first time to submit(?) a file so I can not figure out any better way to give(?) you.

Yee,
sfs131010(HBpencil235)

**Comment by Tamaized** [comment]
For future reference, you can submit a Pull Request for these types of things.
https://help.github.com/articles/creating-a-pull-request-from-a-fork/
