### ISSUE TITLE
AoV 0.8.3 - Astro loses currently selected cards/modifiers upon disconnect/relog to dedicated server

### ISSUE THREAD

**Issue by Not-February** [Tamaized/AoV#47]
Unsure if intended. Just a bit sad when you disconnect due to whatever technical issues tend to arise in a given computer/network environment, and log back in to find everything you've been setting up is now gone.

**Comment by Tamaized** [comment]
Originally intended (not limited to dedicated servers, at least it should be happening in single player upon world exit and rejoin) but I may end up having the data be stored after all.
