### ISSUE TITLE
AoV 0.8.3 - Odd WAILA/HWYLA interaction with Astro

### ISSUE THREAD

**Issue by Not-February** [Tamaized/AoV#49]
This is a bit of an odd one. It took me a while to realize that it was happening whenever I used an Astro ability specifically(I thought it was a completely different mod initially), so I wasn't sure it was just these two mods interacting at first. I also do not know whether it is your mod or HWYLA that is causing the problem.

Basically, I guess when the visuals for Astrologian do some kind of thing where they card is swiped towards the top of the screen, it... _also_ shifts the WAILA tooltip that's on-screen. At first it just gets a little crooked, but then as you keep using different cards and abilities, it gets progressively more and more crooked until it's actually diagonally off the screen and virtually unreadable.

I know for certain that it goes away and the WAILA tooltip returns to normal after a full Minecraft restart, but I would have to double check whether it does so on relog/re-entering a world without closing out of the game first.

This is a weird issue to describe with words alone so I'll try to get some screenshots soon if I can.

**Comment by Tamaized** [comment]
I cant seem to reproduce this issue specifically however I did find another issue causing the waila tooltip to rotate while the redraw animation was active, fixed that and hopefully it indirectly fixes this? no idea but guess we'll find out when I get an update out eventually.

**Comment by Not-February** [comment]
It may well have been that. Hopefully whatever you did will fix it.

**Comment by Tamaized** [comment]
Does this still occur?
