### ISSUE TITLE
[Request] Configurable damage/kill chances

### ISSUE THREAD

**Issue by NielsPilgaard** [Tamaized/AoV#57]
Hey!

Using the Destruction spell on a 800hp Ice and Fire dragon will at the very least deal 400 damage to it, if not one shot it. I would really like a whitelist/blacklist for which entities the spells can oneshot, or if possible, a way to configure the general damage one does.
As a bonus, a way to tie the damage into Difficulty Level from Scaling Health would be awesome, but I realize that's probably very hard, or even impossible. 

I hope you'll consider the suggestions :)

**Comment by Tamaized** [comment]
No longer valid as the spells no longer exist and Implosion has been changed.
