### ISSUE TITLE
Angelic Statue not craft-able?

### ISSUE THREAD

**Issue by ghost** [Tamaized/AoV#63]
Running version: AoV-1.10.2-0.2.5.jar
Minecraft version: 1.10.2

JEI doesn't register any recipes and the provided recipe on your "getting started" doesn't seem to work either. Any ideas?

![2018-02-16_15 11 19](https://user-images.githubusercontent.com/10051871/36327230-f36b370a-132b-11e8-9649-9aa4dcc2d327.png)

**Comment by Tamaized** [comment]
1.10.2 is no longer supported and had another mechanic to craft the statue.

See the really old outdated forum post's getting started area: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2816945-angel-of-vengeance-aov

**Comment by ghost** [comment]
Thanks!
