### ISSUE TITLE
display issue

### ISSUE THREAD

**Issue by Vladimirun** [Tamaized/AoV#7]
display issue Xp / Lvl http://image.noelshack.com/fichiers/2017/18/1493646678-sans-titre.png
for minecraft 1.11.2

**Comment by Tamaized** [comment]
Server or single player?

**Comment by Vladimirun** [comment]
Server , after lvl 7

**Comment by Tamaized** [comment]
I'll look into it, on the bright side, only TamModized will need to be updated

**Comment by Tamaized** [comment]
Actually, just looked over some code. This affects all users on the server at once doesn't it. I apparently did something really silly and so AoV itself needs to be updated, not TamModized.

**Comment by Vladimirun** [comment]
ok, thanks .

**Comment by Tamaized** [comment]
New builds are out (0.1.4) let me know if they fixed both issues as I didn't have time to test them.

**Comment by Vladimirun** [comment]
Its fixed thx for your Works .
