### ISSUE TITLE
Exception in Server Tick Loop

### ISSUE THREAD

**Issue by NielsPilgaard** [Tamaized/AoV#74]
Hey!

A user of mine experienced a crash on his server, the crash seems to point back here:  https://pastebin.com/0gzuce8A 

AoV-1.12-0.8.12
Forge 1.12.2-14.23.2.2645

**Comment by carstorm** [comment]
Can confirm I'm having the same issue: https://pastebin.com/T57YAe4R

Client works fine, crashes on dedicated server.
