### ISSUE TITLE
Crash client when use spell

### ISSUE THREAD

**Issue by Vladimirun** [Tamaized/AoV#8]
when a use spell my friend crash . 
https://pastebin.com/uDSmFjSc

**Comment by Tamaized** [comment]
whoops forgot a null check

**Comment by Vladimirun** [comment]
what do you mean ?

**Comment by Tamaized** [comment]
I forgot a vital piece of code

**Comment by Vladimirun** [comment]
I hope this has helped you . thanks for your mod .
