### ISSUE TITLE
Screen covered in orange and red overlay effect when updated modpack with latest version.

### ISSUE THREAD

**Issue by Darkmega18** [Tamaized/AoV#81]
G'day, I'm having a rather deadly issue right now with updating Angel of vengeance and TamModized in my modpack "Transcendence". You when I logged in after updating I was greeted with this (I was in the process of exploring the twilight forest gathering information for quests):

https://cdn.discordapp.com/attachments/515004683912478733/516155175363280896/unknown.png

After frustratingly trying to get rid of it in other ways, I noticed it was overlaying the gui and other bits in menus making playing basically impossible. so I went out, and since AoV and TamModized were the only other two things I updated i backdated them all to their prior versions before this just past update and it worked as normal.

https://cdn.discordapp.com/attachments/515004683912478733/516166195389399040/unknown.png

Would you know why this occurs? I know the twilight forest uses some special overlays and rain styled particle effects for things like shields and biome lock-out effects but not sure if they're related.

**Comment by Tamaized** [comment]
Thinking another mod is also doing stuff with the Stencil Buffer.

**Comment by Tamaized** [comment]
Poked around with a fresh instance of the modpack, which I believe is this one https://minecraft.curseforge.com/projects/transcendence, along with updating AoV+TamModized manually, I couldn't get the issue to appear.

If you could track down exactly what's causing the issue to arise, even better if you track down the exact mod that's conflicting, that'd be a giant help.

**Comment by Tamaized** [comment]
If it so happens that the issue is with AoV alone, then can you try with this build https://minecraft.curseforge.com/projects/angel-of-vengeance/files/2641172 (when it's approved)

**Comment by Darkmega18** [comment]
you've got the right one. 

Did you try going to the twilight forest? thats where I was when it was happening. under the effects of one of the area denial effects from the biomes when first logging in at the time due to a heap space crash kicking me out just prior, where I then saw the update before restarting the game.

the other mods that were updated were Forgelin and refined storage... among others the previous night but those were the ones updated during the sessions it occured.

**Comment by Tamaized** [comment]
I did and as expected no issues as I know the tf weather effects don't use the stencil buffer. My hunch is that it's a hardware issue that my latest release aims to solve.

Let me know if that build works or not.

**Comment by Darkmega18** [comment]
Roger. I'll try it next time I load the game.

**Comment by Tamaized** [comment]
Assuming fixed.
