### ISSUE TITLE
[1.12.2] Light Level renderings from mods such as "DynamicSurroundings" fail to render.

### ISSUE THREAD

**Issue by SonicX8000** [Tamaized/AoV#83]
Minecraft: 1.12.2
Forge: 14.23.5.2778
Mods: 3

AoV-1.12-0.9.2
DynamicSurroundings-1.12.2-3.4.10.2
TamModized-1.12.2-0.15.6

-----
It seems that Dynamic Surroundings' Light Level viewer fails to render if 'AoV-1.12-0.9.2' is installed. It's not only just Dynamic Surroundings but it seems to also affect More Overlays, Not Enough Item's Mob Spawn Rendering & Light Level Overlay Reloaded.

Here's an image of the bug using 'Dynamic Surroundings'.

![](https://cdn.discordapp.com/attachments/377171551155650560/516622646897803266/AoVconflict.PNG)

Left is with AoV installed, right is without AoV installed. An older version before the current one didn't have this issue if I recall.

*EDIT*
The version I was using before the update was 'AoV-1.12-0.8.14' and the issue doesn't occur. Versions above that and the issue occurs.

**Comment by Tamaized** [comment]
Caused by this line: https://github.com/Tamaized/AoV/blob/247ac44c2d612735774effe12cc847a431c16a36/src/main/java/tamaized/aov/client/gui/AoVOverlay.java#L209

Also affects #84
